# Generated by Django 4.0.4 on 2022-07-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_newpost_delete_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='content',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
