# Generated by Django 4.0.4 on 2022-07-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_newpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='user',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
