# Generated by Django 4.0.4 on 2022-08-04 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_newpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
