# Generated by Django 4.0.4 on 2022-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='view_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
